# Generated by Django 4.2.1 on 2023-06-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id_issuance', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_book', models.BigIntegerField(verbose_name='Id книги')),
                ('id_person', models.BigIntegerField(verbose_name='Id читателя')),
                ('date', models.DateField(verbose_name='Дата выдачи')),
                ('status', models.CharField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Таблица Выдачи',
                'verbose_name_plural': 'Таблица Выдач',
                'db_table': 'issuance',
            },
        ),
    ]
