# Generated by Django 4.2.1 on 2023-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id_notice', models.BigAutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(verbose_name='Фамилия')),
                ('count_books', models.BigIntegerField(verbose_name='Количство подлежащих возврату книг')),
                ('e_mail', models.CharField(verbose_name='E-mail')),
                ('refund_period', models.DateField(verbose_name='Крайняя дата возврата')),
                ('text_in', models.CharField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Таблица Должников',
                'verbose_name_plural': 'Таблица Должников',
                'db_table': 'Должники',
            },
        ),
        migrations.AlterField(
            model_name='issuance',
            name='id_issuance',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
