# Generated by Django 4.2.1 on 2023-08-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_notice_alter_issuance_id_issuance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table='notice',
        ),
    ]
